# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/universal7885-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/universal7885-common/proprietary/lib/libprotobuf-cpp-full.so:system/lib/libprotobuf-cpp-full.so \
    vendor/samsung/universal7885-common/proprietary/lib/libprotobuf-cpp-lite.so:system/lib/libprotobuf-cpp-lite.so \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/00060308060501020000000000000000.tlbin:system/vendor/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin:system/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin:system/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/08130000000000000000000000000000.tlbin:system/vendor/app/mcRegistry/08130000000000000000000000000000.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/FFFFFFFF000000000000000000000001.drbin:system/vendor/app/mcRegistry/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000012.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000013.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000016.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000017.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000019.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000019.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000002f.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000002f.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000038.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000038.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000003e.tlbin_vendor:system/vendor/app/mcRegistry/ffffffff00000000000000000000003e.tlbin_vendor \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000041.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000041.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000045.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000045.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000077.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000077.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/vendor/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:system/vendor/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffffd00000000000000000000045.tlbin:system/vendor/app/mcRegistry/ffffffffd00000000000000000000045.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/app/mcRegistry/ffffffffd00000000000000000000062.tlbin:system/vendor/app/mcRegistry/ffffffffd00000000000000000000062.tlbin \
    vendor/samsung/universal7885-common/proprietary/vendor/bin/hw/gpsd:system/vendor/bin/hw/gpsd \
    vendor/samsung/universal7885-common/proprietary/vendor/bin/mcDriverDaemon:system/vendor/bin/mcDriverDaemon \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/hydra_config.sdb:system/vendor/etc/wifi/hydra_config.sdb \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/indoorchannel.info:system/vendor/etc/wifi/indoorchannel.info \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx:system/vendor/etc/wifi/mx \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140.bin:system/vendor/etc/wifi/mx140.bin \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/common/log-strings.bin:system/vendor/etc/wifi/mx140/debug/common/log-strings.bin \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/hardware/moredump/bt_registers.xml:system/vendor/etc/wifi/mx140/debug/hardware/moredump/bt_registers.xml \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/hardware/moredump/cortexM4.xml:system/vendor/etc/wifi/mx140/debug/hardware/moredump/cortexM4.xml \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/hardware/moredump/cortexR4.xml:system/vendor/etc/wifi/mx140/debug/hardware/moredump/cortexR4.xml \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/hardware/moredump/mailbox16.xml:system/vendor/etc/wifi/mx140/debug/hardware/moredump/mailbox16.xml \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/hardware/moredump/mailbox4.xml:system/vendor/etc/wifi/mx140/debug/hardware/moredump/mailbox4.xml \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/hardware/moredump/mailbox8.xml:system/vendor/etc/wifi/mx140/debug/hardware/moredump/mailbox8.xml \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/hardware/moredump/moredump.xml:system/vendor/etc/wifi/mx140/debug/hardware/moredump/moredump.xml \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/hardware/moredump/pl192vic.xml:system/vendor/etc/wifi/mx140/debug/hardware/moredump/pl192vic.xml \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/hardware/moredump/rf_chip_registers.xml:system/vendor/etc/wifi/mx140/debug/hardware/moredump/rf_chip_registers.xml \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/hardware/moredump/wlan_sys_registers.xml:system/vendor/etc/wifi/mx140/debug/hardware/moredump/wlan_sys_registers.xml \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/wlan/hip_signals.xml:system/vendor/etc/wifi/mx140/debug/wlan/hip_signals.xml \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/wlan/id.txt:system/vendor/etc/wifi/mx140/debug/wlan/id.txt \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/wlan/mib_out.xml:system/vendor/etc/wifi/mx140/debug/wlan/mib_out.xml \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/wlan/symbols.dbg:system/vendor/etc/wifi/mx140/debug/wlan/symbols.dbg \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/wlan/unicli.dbg:system/vendor/etc/wifi/mx140/debug/wlan/unicli.dbg \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/wlan/unitab.dbg:system/vendor/etc/wifi/mx140/debug/wlan/unitab.dbg \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/wlan/univif.dbg:system/vendor/etc/wifi/mx140/debug/wlan/univif.dbg \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140/debug/wlan/xide_mib.dbg:system/vendor/etc/wifi/mx140/debug/wlan/xide_mib.dbg \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140_t_wlan.hcf:system/vendor/etc/wifi/mx140_t_wlan.hcf \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/mx140_wlan.hcf:system/vendor/etc/wifi/mx140_wlan.hcf \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:system/vendor/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/platform.txt:system/vendor/etc/wifi/platform.txt \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/wpa_supplicant.conf:system/vendor/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/universal7885-common/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:system/vendor/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/samsung/universal7885-common/proprietary/vendor/firmware/APBargeIn_AUDIO_SLSI.bin:system/vendor/firmware/APBargeIn_AUDIO_SLSI.bin \
    vendor/samsung/universal7885-common/proprietary/vendor/firmware/AP_AUDIO_SLSI.bin:system/vendor/firmware/AP_AUDIO_SLSI.bin \
    vendor/samsung/universal7885-common/proprietary/vendor/firmware/Tfa9872.cnt:system/vendor/firmware/Tfa9872.cnt \
    vendor/samsung/universal7885-common/proprietary/vendor/firmware/calliope_dram.bin:system/vendor/firmware/calliope_dram.bin \
    vendor/samsung/universal7885-common/proprietary/vendor/firmware/calliope_sram.bin:system/vendor/firmware/calliope_sram.bin \
    vendor/samsung/universal7885-common/proprietary/vendor/firmware/fimc_is_lib.bin:system/vendor/firmware/fimc_is_lib.bin \
    vendor/samsung/universal7885-common/proprietary/vendor/firmware/fimc_is_rta.bin:system/vendor/firmware/fimc_is_rta.bin \
    vendor/samsung/universal7885-common/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/universal7885-common/proprietary/vendor/firmware/setfile_4ha.bin:system/vendor/firmware/setfile_4ha.bin \
    vendor/samsung/universal7885-common/proprietary/vendor/firmware/setfile_5e9.bin:system/vendor/firmware/setfile_5e9.bin \
    vendor/samsung/universal7885-common/proprietary/vendor/firmware/tfadsp.bin:system/vendor/firmware/tfadsp.bin \
    vendor/samsung/universal7885-common/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/universal7885-common/proprietary/vendor/lib/hw/camera.exynos7885.so:system/vendor/lib/hw/camera.exynos7885.so \
    vendor/samsung/universal7885-common/proprietary/vendor/lib/hw/sensors.universal7885.so:system/vendor/lib/hw/sensors.universal7885.so \
    vendor/samsung/universal7885-common/proprietary/lib/libMcClient.so:system/lib/libMcClient.so \
    vendor/samsung/universal7885-common/proprietary/lib/libMcRegistry.so:system/lib/libMcRegistry.so \
    vendor/samsung/universal7885-common/proprietary/vendor/lib/libexynoscamera3.so:system/vendor/lib/libexynoscamera3.so \
    vendor/samsung/universal7885-common/proprietary/vendor/lib/libfloatingfeature.so:system/vendor/lib/libfloatingfeature.so \
    vendor/samsung/universal7885-common/proprietary/vendor/lib/libhwjpeg.so:system/vendor/lib/libhwjpeg.so \
    vendor/samsung/universal7885-common/proprietary/vendor/lib/libsensorlistener.so:system/vendor/lib/libsensorlistener.so \
    vendor/samsung/universal7885-common/proprietary/vendor/lib/libuniapi.so:system/vendor/lib/libuniapi.so \
    vendor/samsung/universal7885-common/proprietary/vendor/lib/libuniplugin.so:system/vendor/lib/libuniplugin.so \
    vendor/samsung/universal7885-common/proprietary/vendor/lib/libwrappergps.so:system/vendor/lib/libwrappergps.so \
    vendor/samsung/universal7885-common/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/universal7885-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/universal7885-common/proprietary/vendor/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/vendor/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/universal7885-common/proprietary/vendor/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/vendor/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/universal7885-common/proprietary/vendor/lib/omx/libOMX.Exynos.HEVC.Encoder.so:system/vendor/lib/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/universal7885-common/proprietary/vendor/lib/omx/libOMX.Exynos.VP9.Decoder.so:system/vendor/lib/omx/libOMX.Exynos.VP9.Decoder.so

ifeq ($(WITH_EXYNOS_BSP),)
endif

# Create Mali links for Vulkan and OpenCL
PRODUCT_PACKAGES += libGLES_mali

# Qualcomm WiFi driver
PRODUCT_PACKAGES += qca_cld_wlan
