# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/klimtlte/setup-makefiles.sh

# International RIL
PRODUCT_COPY_FILES += \
    vendor/samsung/klimtlte/proprietary/blobs/lte/bin/cbd:system/bin/cbd \
    vendor/samsung/klimtlte/proprietary/blobs/lte/lib/libsec-ril.so:system/lib/libsec-ril.so

# Canadian RIL
PRODUCT_COPY_FILES += \
    vendor/samsung/klimtlte/proprietary/blobs/can/bin/cbd:system/bin/cbd \
    vendor/samsung/klimtlte/proprietary/blobs/can/lib/libsec-ril.so:system/lib/libsec-ril.so

# Oceania RIL
PRODUCT_COPY_FILES += \
    vendor/samsung/klimtlte/proprietary/blobs/do/bin/cbd:system/bin/cbd \
    vendor/samsung/klimtlte/proprietary/blobs/do/lib/libsec-ril.so:system/lib/libsec-ril.so

# South Americas RIL
PRODUCT_COPY_FILES += \
    vendor/samsung/klimtlte/proprietary/blobs/ub/bin/cbd:system/bin/cbd \
    vendor/samsung/klimtlte/proprietary/blobs/ub/lib/libsec-ril.so:system/lib/libsec-ril.so

# Sensors
PRODUCT_COPY_FILES += \
    vendor/samsung/klimtlte/proprietary/lib/hw/sensors.universal5420.so:system/lib/hw/sensors.universal5420.so

# Noise suppression
PRODUCT_COPY_FILES += \
    vendor/samsung/klimtlte/proprietary/vendor/etc/nxp/mVoIP/Tx_ControlParams_WIDEBAND_EARPIECE.txt:system/vendor/etc/nxp/mVoIP/Tx_ControlParams_WIDEBAND_EARPIECE.txt \
    vendor/samsung/klimtlte/proprietary/vendor/etc/nxp/mVoIP/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/mVoIP/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt