#
# Copyright 2016 The CyanogenMod Project
# Copyright 2017-2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file is generated by device/samsung/gta3xlwifi/setup-makefiles.sh
LOCAL_PATH := vendor/samsung/gta3xlwifi
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/vendor/lib/hw/camera.exynos7885.so:system/vendor/lib/hw/camera.exynos7885.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libexynoscamera3.so:system/vendor/lib/libexynoscamera3.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsecnativefeature.so:system/vendor/lib/libsecnativefeature.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/hw/sensors.universal7885.so:system/vendor/lib/hw/sensors.universal7885.so \
    $(LOCAL_PATH)/proprietary/vendor/etc/wifi/mx140.bin:system/vendor/etc/wifi/mx140.bin \
    $(LOCAL_PATH)/proprietary/vendor/etc/wifi/mx140_t.bin:system/vendor/etc/wifi/mx140_t.bin
