# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/klimttd/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/klimttd/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/samsung/klimttd/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/klimttd/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/klimttd/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/klimttd/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/klimttd/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/klimttd/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/klimttd/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/samsung/klimttd/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/klimttd/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/klimttd/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/klimttd/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/klimttd/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/klimttd/proprietary/bin/efsks:system/bin/efsks \
    vendor/samsung/klimttd/proprietary/bin/diag_uart_log:system/bin/diag_uart_log \
    vendor/samsung/klimttd/proprietary/bin/diag_mdlog:system/bin/diag_mdlog \
    vendor/samsung/klimttd/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/samsung/klimttd/proprietary/bin/ks_9x15:system/bin/ks_9x15 \
    vendor/samsung/klimttd/proprietary/bin/qcks:system/bin/qcks \
    vendor/samsung/klimttd/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/klimttd/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/klimttd/proprietary/bin/smdexe:system/bin/smdexe \
    vendor/samsung/klimttd/proprietary/lib/libcsd-client.so:system/bin/libcsd-client.so \
    vendor/samsung/klimttd/proprietary/lib/libprotobuf-cpp-full.so:system/lib/libprotobuf-cpp-full.so \
    vendor/samsung/klimttd/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/klimttd/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/klimttd/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/samsung/klimttd/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/klimttd/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/klimttd/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/klimttd/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/klimttd/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/klimttd/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/klimttd/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/samsung/klimttd/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/samsung/klimttd/proprietary/lib/libloc_core.so:system/lib/libloc_core.so \
    vendor/samsung/klimttd/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/samsung/klimttd/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/samsung/klimttd/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/samsung/klimttd/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/samsung/klimttd/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/samsung/klimttd/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/samsung/klimttd/proprietary/lib/libxml.so:system/lib/libxml.so \
    vendor/samsung/klimttd/proprietary/lib/libmdmdetect.so:system/lib/libmdmdetect.so \
    vendor/samsung/klimttd/proprietary/etc/Diag_audio.cfg:system/etc/Diag_audio.cfg \
    vendor/samsung/klimttd/proprietary/etc/Diag_gps.cfg:system/etc/Diag_gps.cfg \
    vendor/samsung/klimttd/proprietary/etc/Diag_volte.cfg:system/etc/Diag_volte.cfg \
    vendor/samsung/klimttd/proprietary/etc/Diag_wifi.cfg:system/etc/Diag_wifi.cfg \
    vendor/samsung/klimttd/proprietary/etc/Diag_zero.cfg:system/etc/Diag_zero.cfg \
    vendor/samsung/klimttd/proprietary/etc/plmn_delta.bin:system/etc/plmn_delta.bin \
    vendor/samsung/klimttd/proprietary/etc/plmn_se13.bin:system/etc/plmn_se13.bin \
    vendor/samsung/klimttd/proprietary/etc/srm.bin:system/etc/srm.bin \
    vendor/samsung/klimttd/proprietary/lib/hw/sensors.universal5420.so:system/lib/hw/sensors.universal5420.so
